### ISSUE TITLE
latest gamescope wouldn't run. It just crashes

### ISSUE THREAD

**Issue by Roddyboii** [flathub/com.valvesoftware.Steam.Utility.gamescope#12]
I want to use the latest flatpak gamescope because of the new FSR feature. The version before this works but the newest one just crashes regardless if the game is native or using proton-ge.

I'm using an AMD apu right now (Ryzen 5 3400G) running on Fedora Linux. I have everything up to date including Steam Flatpak and Fedora. I don't know how to send or even find the logs but Fedora's problem reporting app did find out that it crashed.

**Comment by Roddyboii** [comment]
I managed to figure out where the logs are.

var_log_messages: https://pastebin.com/ZPR3Kpse
cpuinfo: https://pastebin.com/iY6iByN7
core_backtrace: https://pastebin.com/4mwTCVh1

**Comment by Equivocal90** [comment]
I believe I'm having the same issue. Latest gamescope crashes. Downgrading to the previous version works as normal.
I am on Fedora Silverblue 35. Also, on an AMD GPU (6800 XT).

**Comment by xinyazhang** [comment]
Thanks for your reporting. I'm able to reproduce this problem locally. (but not sure when I had time to actually fix it).

**Comment by Roddyboii** [comment]
UPDATE. Disabling the steam overlay fixes the issue. So the logs we're (i think) right about it.

**Comment by xinyazhang** [comment]
It seems this issue is related to Plagman/gamescope/#382, and I've updated gamescope to 3.11.19 (Higher versions did not pass their own CI and it seems the upstream is still ramping up new releases).
@Roddyboii did this solve your problem?

**Comment by Roddyboii** [comment]
Just tested today and it indeed works now with the overlay enabled. Thanks!
