### ISSUE TITLE
Running with flatpak MangoHud installed causes a crash

### ISSUE THREAD

**Issue by SeriousBug** [flathub/com.valvesoftware.Steam.Utility.gamescope#13]
To reproduce the error, install the flatpak versions of Steam, MangoHud, and gamescope. Then in a Wayland compositor (I'm using sway), run a game with gamescope. Or alternatively, launch a shell with `flatpak run --command /bin/bash com.valvesoftware.Steam` and then run `gamescope` inside the shell. It will immediately crash with a segmentation fault.

Uninstalling MangoHud, then restarting Steam fixes the issue.

If I can provide any additional information to help debug this, please let me know. Or if this just isn't supported alongside MangoHud right now, I think that can be added to the Readme.

Anyway, thanks to the packager and all the contributors, it's awesome!

**Comment by xinyazhang** [comment]
Hi @SeriousBug
Have you tried gamescope without MangoHud. It seems this bug persists without flatpak (https://github.com/Plagman/gamescope/issues/400)

**Comment by SeriousBug** [comment]
That seems to work, thanks!
