### ISSUE TITLE
gamescope 3.11.32 (NVIDIA Support)

### ISSUE THREAD

**Issue by Bananaman** [flathub/com.valvesoftware.Steam.Utility.gamescope#16]
Hi everyone! There's a big new update for Gamescope, and this Flatpak version is a bit behind.

Gamescope 3.11.32 (stable) is out now and has NVIDIA support. :heart: 

Here's a screenshot of gamescope rendering on NVIDIA: https://twitter.com/Plagman2/status/1524480478408953856

You also need NVIDIA driver 515.48.07, released on May 31st, 2022: https://www.nvidia.com/Download/driverResults.aspx/189809/en-us

For Fedora users, that driver is in RPM Fusion's testing since June 1st, so it'll be out soon.

Reference for why that driver is needed (it was some driver bug): https://github.com/Plagman/gamescope/issues/492#issuecomment-1142371068

When you have that driver, gamescope 3.11.32 will "just work" for NVIDIA users immediately.

**Comment by nicokimmel** [comment]
Arch is on 515.48.07 for about a week now. Would be nice to see an update in the near future.

**Comment by VarLad** [comment]
> For Fedora users, that driver is in RPM Fusion's testing since June 1st, so it'll be out soon.

@Bananaman Any source on that?

**Comment by nicokimmel** [comment]
This should include 3.11.32 until its officially updated.

```flatpak install --user https://dl.flathub.org/build-repo/94391/com.valvesoftware.Steam.Utility.gamescope.flatpakref```
