### ISSUE TITLE
[Request]: Package Gamescope under `org.freedesktop` extension point

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.valvesoftware.Steam.Utility.gamescope#59]
While this flatpak is specifically intended to be used by Steam, it'd be great if it can be moved to the `org.freedesktop.SOMETHING` extension point and package per branch, as [Bottles](https://github.com/bottlesdevs/Bottles/blob/df2a47e72cbbd352c87ecc714622b53768222ed8/com.usebottles.bottles.dev.yml#L44) and [Lutris](https://github.com/flathub/net.lutris.Lutris/blob/1d560df42f3b73216855e0d822b6981b1167eb96/net.lutris.Lutris.yml#L51) support Gamescope. GNOME 42 runtime is based on freedesktop.org runtime 21.08, whereas this flatpak is now based on 22.08. This causes Gamescope to crash within Bottles and Lutris, as seen by https://github.com/flathub/net.lutris.Lutris/issues/271 and https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/58, because of incompatible runtimes. [MangoHud](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud) for example supports 21.08 _and_ 22.08 because the extension point allows us to do that.

**Comment by Doomsdayrs** [comment]
Coming from WarThunder, #58 breaks the game

**Comment by travier** [comment]
I came here to ask for that too. I'm interested in doing the work to make that happen.

Maybe we start by copying this package and submitting it as an FreeDesktop extension directly?

**Comment by TheEvilSkeleton** [comment]
That could work. I also found this manifest from someone I follow: https://github.com/tinywrkb/org.freedesktop.Platform.VulkanLayer.GameScope. This could help us out maybe?

**Comment by travier** [comment]
Yes, we basically need submit that and add a 21.08 branch.

**Comment by travier** [comment]
@tinywrkb Thanks for adding a detailed explanation in your extension repo. Reading it, I'm not sure how we should proceed. We need this for Bottles & Lutris at least and some other use cases might come up.

**Comment by travier** [comment]
I'm still leaning on submitting this as having something that works most of the time with caveats is better than the status quo where it just does not work for the apps mentioned above.

**Comment by tinywrkb** [comment]
> @tinywrkb Thanks for adding a detailed explanation in your extension repo. Reading it, I'm not sure how we should proceed. We need this for Bottles & Lutris at least and some other use cases might come up.

No problem. I thought someone else might want it, so I tried doing my best in documenting this.

For my use case, running any app with GameScope, I think a temporary solution of a runtime extension is acceptable, but going forward I would like to see the compositor included in the runtime.  
We can't really add this now to the runtime add the added shared libs will possibly be picked up by buildsystems and enable auto config features when building applications, meaning runtime downgrade will break applications.

For specific applications that need GameScope, and won't be run correctly without it, I think it would be better to add it as a new base application or to an existing one, like the `org.winehq.Wine`.  
I do not like the idea of having shared libs in an extension. I think it's only acceptable when you make sure that ABI is compatible, like it's done with the FFmpeg-full extension.

**Comment by orowith2os** [comment]
What's the current take on this issue? Just let the apps themselves bundle Gamescope?

**Comment by travier** [comment]
If you're not using the same runtime as the Steam one then you should probably bundle Gamescope in your app for now until this is submitted as discussed here.

**Comment by orowith2os** [comment]
See https://github.com/flathub/flathub/pull/4329 for an attempt at this. I've also opened https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/pull/150 for when it's merged.

**Comment by orowith2os** [comment]
Done, at https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.gamescope

**Comment by TheEvilSkeleton** [comment]
Closing
